# Generated by Django 4.0.3 on 2022-05-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='yes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='Software Engineer', max_length=24),
        ),
    ]
