# Generated by Django 4.0.3 on 2022-05-18 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_image_remove_profile_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='qr_codes/'),
            preserve_default=False,
        ),
    ]
