# Generated by Django 4.0.4 on 2022-05-22 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
