"""
Django settings for nautprofile project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*k7elw6de+24^2uij$-vpkq#g!n22+xbpufl@q)7*!l5ch^ofk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'profiles',
    'qr_code',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nautprofile.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nautprofile.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'nautprofie',
        'USER':'postgres',
        'PASSWORD':'Nautilus5he!',
        'HOST':'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
MEDAIA_ROOT=os.path.join(BASE_DIR,'staticfiles')

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static/')
]
# STATIC_ROOT=os.path.join(BASE_DIR,'static/')

MEDIA_URL ="/media/"
MEDAIA_ROOT=os.path.join(BASE_DIR,'media/')

CRISPY_TEMPLATE_PACK = 'bootstrap3'

EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT='465'
EMAIL_HOST_USER='adedamolabasit09@gmail.com'
EMAIL_HOST_PASSWORD='Blackhack1!'
EMAIL_USE_TLS=False
EMAIL_USE_SSL=True



AWS_ACCESS_KEY_ID='AKIAV655YNHELYBULKGW'
AWS_SECRET_ACCESS_KEY='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'
AWS_STORAGE_BUCKET_NAME="nautilus-profile"

AWS_S3_FILE_OVERWRITE=False
AWS_DEFAULT_ACL=None
# AWS_S3_REGION_NAME = 'us-east-2'
# AWS_S3_ADDRESSING_STYLE = 'virtual'
# AWS_S3_SIGNATURE_VERSION = 's3v4'

DEFAULT_FILE_STORAGE ='storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE='storages.backends.s3boto3.s3BotoStorage'